added dataset
bliutech/SeBRUS pull request #31
Opened 2023-07-13 19:46 UTC by ChL4859

Benson, can you please check to see if this looks good? Thank you! :D

2023-07-13 19:50 UTC, bliutech requested changes
Hey @ChL4859! I think you may have forgotten to run some `git` commands. Currently, I don't see any changes. Try running the following commands.

```
git add -A
git commit -m "your commit message"
git push
```

2023-07-13 19:59 UTC, ChL4859 commented
ahh I fixed it, can you see the changes now? it should be under "added dataset updated"

2023-07-13 20:21 UTC, bliutech requested changes
@ChL4859 Nice start! You probably were running into some issues with being able to run `app.py` to try and test your code so I updated merged this branch with @trishavreddy's branch to try and help you get started here. You will need to update a few things so I recommend checking out some of the implementations of `models/user.py` and `routes/user.py` to try and see what the code pattern looks like and perform updates from there.

2023-07-13 20:22 UTC, bliutech commented on server/models/dataset.py
> +        count = id
I believe you have this flipped around. I think you are trying to make `self.id = Dataset.count`. :D

2023-07-13 20:24 UTC, bliutech commented on server/routes/dataset.py
> +    from models.dataset import Dataset
So this may be a little bit confusing but the reason why we need to put these here instead of at the top of the document is because of a problem that will happen involving circular dependencies. `Dataset` relies upon `db` in `app.py` but `app.py` relies upon `Dataset` when running as main. To resolve some of these issues, you take advantage of dynamic imports with Python. 😄

2023-07-13 20:24 UTC, bliutech commented on server/app.py
> +    # TODO: Replace this implementation with a call to the dataset router
Make sure to add your call to `dataset.router` here. 👍

2023-07-13 20:26 UTC, bliutech commented on server/models/user.py
> +        # account for existing users before class is first initialized
I recommend adding something similar to `dataset.py`. This may be a little bit confusing but basically this allows us to use the same SQLite file for different runs. When the class is first initialized, it sets count to 0 cause a collision in ids. For this reason, we have to check the existing SQLite database to see how many users we have in order to start the count again.

2023-07-13 20:27 UTC, bliutech commented on server/routes/user.py
> +        if id == "all":
I may have forgotten to mention this in the initial issue but I recommend supporting this `all` id.

2023-07-14 02:23 UTC, Herefersomepennys approved these changes

2023-07-14 02:45 UTC, bliutech requested changes
@ChL4859 I think you accidentally cloned a copy of the repository inside your local copy of your repository. 😄 Be careful though. You don't want to lose your changes. Currently you will see your repository structure look something like this.

```
gset23/
...
      server/
      ...
            gset23/
```

I currently don't see any changes from the comments I made last time I examined this PR so I think you may have made the changes inside the inner `gset23/` folder. You are going to want to do the following to make sure that everything gets saved okay.

Make sure you start off inside the inner `gset23/` folder. Use `cd` to do this.

```
gset23/
...
      server/
      ...
            gset23/ (this one right here)
```

Verify you are in the right place with by running `pwd`. If you don't see a long path that looks something like this. `<start of the path>/gset23/server/gset23` then you are in the wrong place. Make sure to move to the right place. You are inside the right directory, run `git diff`. If this outputs anything, then my hypothesis above is correct. If it outputs nothing, then ping me on Discord. We will need to chat to try and resolve this since it is different then what I might have thought. If everything looks okay, let's try and fix things.

1. Make sure you are on the right branch.  `git branch` should tell you that you are on `dataset`. If not then use `git checkout dataset`.
2. Make sure that your branch is up to date. Run `git pull`.
3. Commit your changes. `git add -A / git commit -m "your message" / git push` should hopefully allow your to push your last few changes to this branch. 👍

2023-07-14 06:05 UTC, bliutech submitted a review, later dismissed
Quick clarification. I realized I misunderstood something about the code layout so hopefully I was able to clean up the repository to see your changes. I also saw you began implementing `/api/abi/<id>` on this PR. We try to break up features into multiple pull requests so I recommend finishing up this PR and then tackling these other changes on another branch after we have merged. That being said, I added the pseudocode for the other endpoint to get you started. 👍

2023-07-14 06:08 UTC, bliutech commented on server/app.py
> +#     return dataset.router(id)
This is what the intended call of `router` should look like. It passes variables that appear in the URL rather than every item. The difference is is that `<id>` here is what's known as a path parameter whereas the parameters you are currently passing down to your implementation are parameters part of the JSON body.

2023-07-14 06:09 UTC, bliutech commented on server/models/dataset.py
> +        count = id
Make sure to make this fix!

2023-07-14 06:10 UTC, bliutech commented on server/models/dataset.py
> +        count = id
I also recommend implementing similar logic here from https://github.com/bliutech/gset23bsg/blob/dataset/server/models/user.py#L14C1-L17C32. This is a necessary edge case to account for.

2023-07-14 06:10 UTC, bliutech commented on server/models/dataset.py
> +    count = 0
Let's also try to indicate make this a private variable by calling it `_count`

2023-07-14 06:11 UTC, bliutech commented on server/models/dataset.py
> +        count = id
See https://github.com/bliutech/gset23bsg/pull/31/files#r1263023046 for explanation.

2023-07-14 06:13 UTC, bliutech commented on server/routes/dataset.py
> +def router(dataset_id, dataset_datasetName, dataset_description, dataset_address):
The interface that should be defined here is `router(id)`. Same goes for `get(id)`,`put(id)`, and `delete(id)`. POST can just be `post()`. The reason for this is so we can handle the path variable. Everything else we will be able to retrieve from `request.json`.

2023-07-14 06:15 UTC, bliutech commented on server/routes/dataset.py
> +        new_dataset.save_to_db()
This syntax I believe is correct. Make sure to encapsulate everything in `app.app_context()`. See https://github.com/bliutech/gset23bsg/pull/31/files#diff-9dd4de54038dbc40cba18b816840301ddc65327d5129ede909ef5927a746a875 for some hints on how to do this.

2023-07-14 06:18 UTC, bliutech commented on server/routes/dataset.py
> +    dataset = Dataset.query.filter_by(id=dataset_id).first()
This is something I just found out recently as well so its something that we need to tackle. SQLAlchemy bases all queries as part of sessions which require a specific application context. For that reason, we need to add

```python
from app import app, db

with app.app_context():
      datasets = db.session.query(Dataset).all()
```

See https://github.com/bliutech/gset23bsg/pull/31/files#diff-9dd4de54038dbc40cba18b816840301ddc65327d5129ede909ef5927a746a875 for a reference.

2023-07-14 06:19 UTC, bliutech commented on server/routes/dataset.py
> +def get(dataset_id, dataset_datasetName, dataset_description, dataset_address):
Update the interface to be `get(id)`

2023-07-14 06:19 UTC, bliutech commented on server/routes/dataset.py
> +def post(dataset_id, dataset_datasetName, dataset_description, dataset_address):
Update interface to be `post()`

2023-07-14 06:20 UTC, bliutech commented on server/routes/dataset.py
> +def put(dataset_id, dataset_datasetName, dataset_description, dataset_address):
Add an interface.

2023-07-14 06:21 UTC, bliutech commented on server/routes/dataset.py
> +        return jsonify({}, {"status": "existing dataset"}), 409
Only one Python dictionary should be passed in to `jsonify`. This is where the recommended data structure of ` res = {"status": ""}` I recommend manipulating this and outputting this to `jsonify`.

2023-07-14 06:22 UTC, bliutech commented on server/routes/dataset.py
> +        return jsonify({}, {"status": "existing dataset"}), 409
Apply this change to all implemented functions.

2023-07-14 06:22 UTC, bliutech commented
Make sure to check out the implementation of `user.py` to get an idea of what the code structure should look like @ChL4859! 😄

2023-07-16 23:14 UTC, merged